{{ define "otelcol.config.receiver_name.cluster_events" }}k8sobjects/cluster_events{{ end }}
{{ define "otelcol.config.receiver.cluster_events" }}
{{ include "otelcol.config.receiver_name.cluster_events" . }}:
  objects:
  - name: events
    mode: watch
{{- if .Values.cluster_events.namespaces }}
    namespaces: {{ .Values.cluster_events.namespaces | toJson }}
{{- end }}
{{ end }}

  {{/* breadcrumb: this doesn't quite work. Does k8sattributes work with k8sobjects? */}}
{{ define "otelcol.config.k8sattributes_name.cluster_events" }}k8sattributes/cluster_events{{ end }}
{{ define "otelcol.config.k8sattributes.cluster_events" }}
{{ include "otelcol.config.k8sattributes_name.cluster_events" .}}:
  extract:
    metadata:
      - k8s.namespace.name
      - k8s.pod.name
      - k8s.container.name
{{ end }}

{{ define "otelcol.config.transform_name.cluster_events" }}transform/cluster_events{{ end }}
{{ define "otelcol.config.transform.cluster_events" }}
{{ include "otelcol.config.transform_name.cluster_events" . }}:
  error_mode: ignore
  log_statements:
    - context: resource
      statements:
        - set(attributes["job"], "integrations/kubernetes/eventhandler")
        - set(attributes["k8s.cluster.name"], {{ required ".Values.cluster.name is a required value. Please set it and try again." .Values.cluster.name | quote }})
        - set(attributes["cluster"], {{ required ".Values.cluster.name is a required value. Please set it and try again." .Values.cluster.name | quote }})
{{/*        - set(attributes["namespace"], attributes["k8s.namespace.name"])*/}}
{{/*        - set(attributes["pod"], attributes["k8s.pod.name"])*/}}
{{/*        - set(attributes["container"], attributes["k8s.container.name"])*/}}
{{ end }}

{{ define "otelcol.config.resource_name.cluster_events" }}resource/cluster_events{{ end }}
{{ define "otelcol.config.resource.cluster_events" }}
{{ include "otelcol.config.resource_name.cluster_events" .}}:
  attributes:
    - action: insert
      key: loki.resource.labels
      value: job, k8s.cluster.name, cluster, namespace, pod, container
{{ end }}
