{{ define "otelcol.config.scrape_config.kube_state_metrics" }}
- job_name: integrations/kubernetes/kube-state-metrics
  scrape_interval: {{ (index .Values.metrics "kube-state-metrics").scrapeInterval | default .Values.metrics.scrapeInterval | quote }}
  kubernetes_sd_configs:
    - role: service
  relabel_configs:
{{- if (index .Values "kube-state-metrics").enabled }}
    - source_labels: ["__meta_kubernetes_service_label_app_kubernetes_io_instance"]
      regex: {{ .Release.Name | quote }}
      action: keep
{{- end }}
{{- range $k, $v := (index .Values.metrics "kube-state-metrics").labelMatchers }}
    - source_labels: ["__meta_kubernetes_service_label_{{ include "escape_label" $k }}"]
      regex: {{ $v | quote }}
      action: keep
{{- end }}
    - source_labels: ["__meta_kubernetes_service_port_name"]
      regex: {{ (index .Values.metrics "kube-state-metrics").service.port | quote }}
      action: keep
{{- if .Values.metrics.extraRelabelingRules }}
{{ .Values.metrics.extraRelabelingRules | indent 4 }}
{{- end }}
{{- if (index .Values.metrics "kube-state-metrics").extraRelabelingRules }}
{{ (index .Values.metrics "kube-state-metrics").extraRelabelingRules | indent 4 }}
{{- end }}
  metric_relabel_configs:
    - source_labels: ["__name__"]
      regex: "up|{{ join "|" (index .Values.metrics "kube-state-metrics").allowList }}"
      action: keep
{{- if .Values.metrics.extraMetricRelabelingRules }}
{{ .Values.metrics.extraMetricRelabelingRules | indent 4 }}
{{- end }}
{{- if (index .Values.metrics "kube-state-metrics").extraMetricRelabelingRules }}
{{ (index .Values.metrics "kube-state-metrics").extraMetricRelabelingRules | indent 4 }}
{{- end }}
{{ end }}
