{{ define "otelcol.config.scrape_config.node_exporter" }}
- job_name: integrations/node_exporter
  scrape_interval: {{ (index .Values.metrics "node-exporter").scrapeInterval | default .Values.metrics.scrapeInterval | quote }}
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
{{- if (index .Values "prometheus-node-exporter").enabled }}
    - source_labels: ["__meta_kubernetes_pod_label_app_kubernetes_io_instance"]
      regex: {{ .Release.Name | quote }}
      action: keep
{{- end }}
{{- range $k, $v := (index .Values.metrics "node-exporter").labelMatchers }}
    - source_labels: ["__meta_kubernetes_pod_label_{{ include "escape_label" $k }}"]
      regex: {{ $v | quote }}
      action: keep
{{- end }}
    - source_labels: ["__meta_kubernetes_pod_node_name"]
      action: replace
      target_label: "instance"
{{- if .Values.metrics.extraRelabelingRules }}
{{ .Values.metrics.extraRelabelingRules | indent 4 }}
{{- end }}
{{- if (index .Values.metrics "node-exporter").extraRelabelingRules }}
{{ (index .Values.metrics "node-exporter").extraRelabelingRules | indent 4 }}
{{- end }}
  metric_relabel_configs:
    - source_labels: ["__name__"]
      regex: "up|{{ join "|" (index .Values.metrics "node-exporter").allowList }}"
      action: keep
{{- if .Values.metrics.extraMetricRelabelingRules }}
{{ .Values.metrics.extraMetricRelabelingRules | indent 4 }}
{{- end }}
{{- if (index .Values.metrics "node-exporter").extraMetricRelabelingRules }}
{{ (index .Values.metrics "node-exporter").extraMetricRelabelingRules | indent 4 }}
{{- end }}
{{ end }}
