cluster:
  name: my-cluster

metrics:
  enable: true
  prometheus:
    host: https://prom.example.com
    username: "12345"
    password: "It's a secret to everybody"

  # https://github.com/kubernetes/kube-state-metrics/tree/main/docs#exposed-metrics
  kube_state_metrics:
    enable: true
    allowList:
    - kube_daemonset.*
    - kube_deployment_metadata_generation
    - kube_deployment_spec_replicas
    - kube_deployment_status_observed_generation
    - kube_deployment_status_replicas_available
    - kube_deployment_status_replicas_updated
    - kube_horizontalpodautoscaler_spec_max_replicas
    - kube_horizontalpodautoscaler_spec_min_replicas
    - kube_horizontalpodautoscaler_status_current_replicas
    - kube_horizontalpodautoscaler_status_desired_replicas
    - kube_job.*
    - kube_namespace_status_phase
    - kube_namespace_status_phase
    - kube_node.*
    - kube_persistentvolumeclaim_resource_requests_storage_bytes
    - kube_pod_container_info
    - kube_pod_container_resource_limits
    - kube_pod_container_resource_requests
    - kube_pod_container_status_restarts_total
    - kube_pod_container_status_waiting_reason
    - kube_pod_container_status_waiting_reason
    - kube_pod_info
    - kube_pod_owner
    - kube_pod_start_time
    - kube_pod_status_phase
    - kube_pod_status_phase
    - kube_pod_status_reason
    - kube_replicaset.*
    - kube_resourcequota
    - kube_statefulset.*

  node_exporter:
    enable: true
    allowList:
    - node_cpu.*
    - node_exporter_build_info
    - node_filesystem.*
    - node_memory.*
    - node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate
    - node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate
    - node_namespace_pod_container:container_memory_cache
    - node_namespace_pod_container:container_memory_rss
    - node_namespace_pod_container:container_memory_swap
    - node_namespace_pod_container:container_memory_working_set_bytes
    - node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile
    - process_cpu_seconds_total
    - process_resident_memory_bytes

  # https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/documentation/documentation.md
  kubelet:
    enable: true
    allowList:
    - cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits
    - cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests
    - cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests
    - cluster:namespace:pod_memory:active:kube_pod_container_resource_limits
    - cluster:namespace:pod_memory:active:kube_pod_container_resource_requests
    - container_cpu_usage_seconds_total
    - kubelet_certificate_manager_client_expiration_renew_errors
    - kubelet_certificate_manager_client_ttl_seconds
    - kubelet_certificate_manager_server_ttl_seconds
    - kubelet_cgroup_manager_duration_seconds_bucket
    - kubelet_cgroup_manager_duration_seconds_count
    - kubelet_node_config_error
    - kubelet_node_name
    - kubelet_pleg_relist_duration_seconds_bucket
    - kubelet_pleg_relist_duration_seconds_count
    - kubelet_pleg_relist_interval_seconds_bucket
    - kubelet_pod_start_duration_seconds_bucket
    - kubelet_pod_start_duration_seconds_count
    - kubelet_pod_worker_duration_seconds_bucket
    - kubelet_pod_worker_duration_seconds_count
    - kubelet_running_container_count
    - kubelet_running_containers
    - kubelet_running_pod_count
    - kubelet_running_pods
    - kubelet_runtime_operations_errors_total
    - kubelet_runtime_operations_total
    - kubelet_server_expiration_renew_errors
    - kubelet_volume_stats_available_bytes
    - kubelet_volume_stats_capacity_bytes
    - kubelet_volume_stats_inodes
    - kubelet_volume_stats_inodes_used
    - kubernetes_build_info
    - namespace_cpu:kube_pod_container_resource_limits:sum
    - namespace_cpu:kube_pod_container_resource_requests:sum
    - namespace_cpu:kube_pod_container_resource_requests:sum
    - namespace_memory:kube_pod_container_resource_limits:sum
    - namespace_memory:kube_pod_container_resource_requests:sum
    - namespace_workload_pod
    - namespace_workload_pod:kube_pod_owner:relabel
    - rest_client_requests_total
    - storage_operation_duration_seconds_count
    - storage_operation_errors_total
    - volume_manager_total_volumes

  # https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md
  cadvisor:
    enable: true
    allowList:
    - container_cpu_cfs_periods_total
    - container_cpu_cfs_throttled_periods_total
    - container_cpu_usage_seconds_total
    - container_fs_reads_bytes_total
    - container_fs_reads_total
    - container_fs_writes_bytes_total
    - container_fs_writes_total
    - container_memory_cache
    - container_memory_rss
    - container_memory_swap
    - container_memory_working_set_bytes
    - container_network_receive_bytes_total
    - container_network_receive_packets_dropped_total
    - container_network_receive_packets_total
    - container_network_transmit_bytes_total
    - container_network_transmit_packets_dropped_total
    - container_network_transmit_packets_total
    - machine_memory_bytes

  cost:
    enable: true
    allowList:
    - container_cpu_allocation
    - container_gpu_allocation
    - container_memory_allocation_bytes
    - deployment_match_labels
    - kubecost_cluster_info
    - kubecost_cluster_management_cost
    - kubecost_cluster_memory_working_set_bytes
    - kubecost_http_requests_total
    - kubecost_http_response_size_bytes
    - kubecost_http_response_time_seconds
    - kubecost_load_balancer_cost
    - kubecost_network_internet_egress_cost
    - kubecost_network_region_egress_cost
    - kubecost_network_zone_egress_cost
    - kubecost_node_is_spot
    - node_cpu_hourly_cost
    - node_gpu_count
    - node_gpu_hourly_cost
    - node_ram_hourly_cost
    - node_total_hourly_cost
    - opencost_build_info
    - pod_pvc_allocation
    - pv_hourly_cost
    - service_selector_labels
    - statefulSet_match_labels

logs:
  enable: true
  loki:
    host: https://loki.example.com
    username: "12345"
    password: "It's a secret to everybody"

  pod_logs:
    enable: true

    # Choose docker or cri (https://grafana.com/docs/agent/latest/flow/reference/components/loki.process/#stagecri-block)
    loggingFormat: docker

  cluster_events:
    enable: true

# extraConfig can be used to add additional configuration to the Grafana Agent
extraConfig: null

grafana-agent:
  agent:
    configMap:
      create: false
    mounts:
      extra:
      - name: grafana-agent-credentials
        mountPath: /etc/grafana-agent-credentials
  controller:
    volumes:
      extra:
      - name: grafana-agent-credentials
        secret:
          secretName: grafana-agent-credentials

opencost:
  opencost:
    exporter:
      defaultClusterId: my-cluster
      extraEnv:
        CLOUD_PROVIDER_API_KEY: AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U
        EMIT_KSM_V1_METRICS: "false"
        EMIT_KSM_V1_METRICS_ONLY: "true"
        PROM_CLUSTER_ID_LABEL: cluster
    prometheus:
      username: "12345"
      password: "It's a secret to everybody"
      external:
        enabled: true
        url: "https://prom.example.com/api/prom"
      internal: { enabled: false }
    ui: { enabled: false }
