{{ define "otelcollector.config.kube_state_metrics" }}
- job_name: integrations/kubernetes/kube-state-metrics
  scrape_interval: {{ (index .Values.metrics "kube-state-metrics").scrapeInterval | default .Values.metrics.scrapeInterval }}
  kubernetes_sd_configs:
    - role: service
  relabel_configs:
{{- if (index .Values "kube-state-metrics").enabled }}
    - action: keep
      regex: "{{ .Release.Name }}"
      source_labels: ["__meta_kubernetes_service_label_app_kubernetes_io_instance"]
{{- end }}
    - action: keep
      regex: kube-state-metrics
      source_labels: ["__meta_kubernetes_service_label_app_kubernetes_io_name"]
{{- range $k, $v := (index .Values.metrics "kube-state-metrics").labelMatchers }}
    - action: keep
      regex: "{{ $v }}"
      source_labels: ["__meta_kubernetes_service_label_{{ $k | replace "." "_" | replace "/" "_" }}"]
{{- end }}
    - action: keep
      regex: "{{- (index .Values.metrics "kube-state-metrics").service.port -}}"
      source_labels: ["__meta_kubernetes_service_port_name"]
{{- if .Values.metrics.extraRelabelingRules }}
{{ .Values.metrics.extraRelabelingRules | indent 4 }}
{{- end }}
{{- if (index .Values.metrics "kube-state-metrics").extraRelabelingRules }}
{{ (index .Values.metrics "kube-state-metrics").extraRelabelingRules | indent 4 }}
{{- end }}
{{- if (index .Values.metrics "kube-state-metrics").service.isTLS }}
  scheme: https
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: false
    server_name: kubernetes
{{- end }}
  metric_relabel_configs:
{{- if (index .Values.metrics "kube-state-metrics").allowList }}
    - action: keep
      source_labels: ["__name__"]
      regex: "up|{{ join "|" (index .Values.metrics "kube-state-metrics").allowList }}"
{{- end }}
{{- if .Values.metrics.extraMetricRelabelingRules }}
{{ .Values.metrics.extraMetricRelabelingRules | indent 4 }}
{{- end }}
{{- if (index .Values.metrics "kube-state-metrics").extraMetricRelabelingRules }}
{{ (index .Values.metrics "kube-state-metrics").extraMetricRelabelingRules | indent 4 }}
{{- end }}
{{ end }}
