cluster:
  name: otel-collector-test

externalServices:
  prometheus:
    host: https://prometheus.example.com
    basicAuth:
      username: 12345
      password: "It's a secret to everyone"
  loki:
    host: https://loki.example.com
    basicAuth:
      username: 12345
      password: "It's a secret to everyone"

grafana-agent:
  enabled: false

grafana-agent-logs:
  enabled: false

opentelemetry-collector:
  enabled: true

opentelemetry-collector-logs:
  enabled: true
