cluster:
  name: metrics-only-test

externalServices:
  prometheus:
    host: https://prometheus.example.com
    tenantId: 1000
    basicAuth:
      username: '12345'
      password: It's a secret to everyone

logs:
  enabled: false

grafana-agent:
  enabled: false
grafana-agent-logs:
  enabled: false
opentelemetry-collector:
  enabled: true
opentelemetry-collector-logs:
  enabled: false
