apiVersion: v1
kind: Secret
metadata:
  name: grafana-agent-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- if .Values.metrics.enable }}
  prometheus_host: {{ .Values.metrics.prometheus.host | b64enc | quote }}
  prometheus_username: {{ .Values.metrics.prometheus.username | b64enc | quote }}
  prometheus_password: {{ .Values.metrics.prometheus.password | b64enc | quote }}
{{- end }}
{{- if .Values.logs.enable }}
  loki_host: {{ .Values.logs.loki.host | b64enc | quote }}
  loki_username: {{ .Values.logs.loki.username | b64enc | quote }}
  loki_password: {{ .Values.logs.loki.password | b64enc | quote }}
{{- end }}
