cluster:
  name: logs-only-test
externalServices:
  loki:
    host: https://loki.example.com
    tenantId: 2000
    basicAuth:
      username: '12345'
      password: It's a secret to everyone
metrics:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-windows-exporter:
  enabled: false
prometheus-operator-crds:
  enabled: false
opencost:
  enabled: false
grafana-agent:
  enabled: false
grafana-agent-logs:
  enabled: false
opentelemetry-collector:
  enabled: true
opentelemetry-collector-logs:
  enabled: true
